Repository hazelcast/hazelcast-go-client, pull requests merged in 2018-05, with the labels that each got.

#252 fixing opening multiple connections to same address
  internal/cluster.go
  internal/connection_manager.go
  tests/client_test.go
Labels: Type: Defect

#247 implement projection and test
  core/map.go
  core/projection/projection.go
  internal/common/preconditions.go
  internal/map.go
  internal/predicates/factory.go
  internal/predicates/predicates_impl.go
  internal/projection/factory.go
  internal/projection/projections_impl.go
  internal/protocol/map_project.go
  internal/protocol/map_projectwithpredicate.go
  internal/serialization/serialization.go
  serialization/api.go
  start-rc.sh
  tests/proxy/map/map_test.go
  tests/proxy/map/projection_test.go
  tests/util.go
Labels: Type: Documentation, Type: Enhancement

#255 validate listener arguments
  core/api.go
  core/list.go
  core/map.go
  core/multi_map.go
  core/queue.go
  core/replicated_map.go
  core/set.go
  internal/list.go
  internal/map.go
  internal/multi_map.go
  internal/protocol/core.go
  internal/proxy.go
  internal/queue.go
  internal/replicated_map.go
  internal/set.go
  tests/proxy/list/list_test.go
  tests/proxy/map/map_test.go
  tests/proxy/multi_map/multi_map_test.go
  tests/proxy/queue/queue_test.go
  tests/proxy/replicated_map/replicated_map_test.go
  tests/proxy/set/set_test.go
Labels: Type: Documentation, Type: Enhancement

#257 replace exception with error
  internal/invocation.go
Labels: Type: Cleanup

#209 remove chaining from configs
  config/config.go
  config/flake_id_generator_config.go
  samples/org_website_samples/global_serializer_sample.go
  tests/invocation_test.go
  tests/proxy/flake_id_generator/flake_id_generator_test.go
Labels: Type: Enhancement

#260 remove skipNows
  tests/proxy/pn_counter/pn_counter_test.go
Labels: Type: Enhancement

#256 implement aggregators
  .gometalinter.json
  core/aggregator/aggregators.go
  internal/aggregation/aggregator_hook.go
  internal/aggregation/aggregator_impl.go
  internal/aggregation/factory.go
  internal/map.go
  internal/precond/preconditions.go
  internal/precond/preconditions_test.go
  internal/projection/projections_impl.go
  internal/protocol/map_aggregate.go
  internal/protocol/map_aggregatewithpredicate.go
  internal/serialization/serialization.go
  tests/proxy/map/aggregators_test.go
Labels: Type: Documentation, Type: Enhancement

#225 remove unnecessary interfaces from api
  core/api.go
  core/map.go
  core/multi_map.go
  core/replicated_map.go
  core/topic.go
  internal/cluster.go
  internal/map.go
  internal/multi_map.go
  internal/protocol/bufutil/consts.go
  internal/protocol/core.go
  internal/proxy.go
  internal/replicated_map.go
  internal/topic.go
  samples/org_website_samples/topic_sample.go
  samples/topic/topic_example.go
  tests/proxy/map/map_test.go
  tests/proxy/multi_map/multi_map_test.go
  tests/proxy/replicated_map/replicated_map_test.go
  tests/proxy/topic/topic_test.go
Labels: Type: Cleanup

#262 refactor GetMemberList to GetMembers
  core/cluster.go
  internal/cluster.go
  internal/listener.go
  internal/loadbalancer.go
  tests/cluster_test.go
Labels: Type: Cleanup

#264 remove unused includeValue parameter from onEntryEvent
  .gometalinter.json
  internal/map.go
  test/proxy/map/map_test.go
Labels: Type: Cleanup

#265 add subroutine count to soak test
  sample/map_soak.go
Labels: Type: Enhancement

#200 check whether portable factory can create instance
  internal/serialization/default_portable_reader_test.go
  internal/serialization/morphing_portable_reader_test.go
  internal/serialization/portable_serializer.go
  internal/serialization/portable_serializer_test.go
Labels: Type: Defect

#263 remove I from some remaining interfaces
  internal/heartbeat.go
  internal/listener.go
  internal/serialization/object_data.go
  serialization/api.go
  test/heartbeat_test.go
Labels: Type: Cleanup

#268 add new features and fix broken links
  README.md
Labels: Type: Documentation

#269 add aggregator and projection samples
  sample/map/aggregator/aggregator_example.go
  sample/map/projection/projection_example.go
Labels: Type: Enhancement
