Repository hazelcast/hazelcast-go-client, pull requests merged in 2018-04, with the labels that each got.

#207 implement PNCounter and test
  core/member_selector.go
  hazelcast.go
  internal/client.go
  internal/cluster.go
  internal/common/consts.go
  internal/connection_manager.go
  internal/error.go
  internal/invocation.go
  internal/pn_counter.go
  internal/protocol/pncounter_getconfiguredreplicacount.go
  internal/proxy.go
  internal/proxy_manager.go
  internal/vector_clock.go
  tests/proxy/pn_counter/crdt_replication_delayed_config.xml
  tests/proxy/pn_counter/lite_member_config.xml
  tests/proxy/pn_counter/pn_counter_test.go
  tests/util.go
Labels: Type: Enhancement

#210 combine running tests and add dependencies in build sh
  build.sh
  rc/rc.go
Labels: Type: Enhancement

#208 refactor predicates
  core/predicates/predicates.go
  samples/map/predicate/predicate_example.go
  samples/map_soak.go
  samples/org_website_samples/query_sample.go
  tests/proxy/map/map_member_down/map_member_down_test.go
  tests/proxy/map/map_test.go
  tests/proxy/map/predicates_test.go
  tests/proxy/replicated_map/replicated_map_test.go
Labels: Type: Cleanup

#211 replace IPredicate with interface{}
  core/map.go
  core/predicates/predicates.go
  core/replicated_map.go
  internal/map.go
  internal/predicates/predicates_impl.go
  internal/replicated_map.go
  serialization/api.go
  tests/proxy/map/predicates_test.go
Labels: Type: Defect, Type: Enhancement

#218 add IDistributedObject to flakeId
  core/flake_id_generator.go
  samples/flake_id_generator/flake_id_generator_sample.go
Labels: Type: Defect

#219 fix bug in readBool and ReadUInt8
  internal/common/buffer_util_test.go
Labels: Type: Defect

#217 add PNCounter code sample
  samples/pn_counter/pn_counter_example.go
Labels: Type: Enhancement

#221 use iota when possible
  internal/predicates/predicate_hook.go
  internal/serialization/classdef/class_definition.go
Labels: Type: Cleanup

#220 make creating all proxies consistent
  internal/proxy_manager.go
  internal/replicated_map.go
Labels: Type: Cleanup

#233 refactor receiver names according to Go convention
  config/config.go
  config/flake_id_generator_config.go
  core/ringbuffer.go
  internal/client.go
  internal/cluster.go
  internal/connection.go
  internal/connection_manager.go
  internal/flake_id/auto_batcher.go
  internal/flake_id/auto_batcher_test.go
  internal/flake_id_generator.go
  internal/heartbeat.go
  internal/invocation.go
  internal/lifecycle.go
  internal/list.go
  internal/listener.go
  internal/loadbalancer.go
  internal/map.go
  internal/message_builder.go
  internal/partition.go
  internal/protocol/core.go
  internal/protocol/message.go
  internal/proxy.go
  internal/proxy_manager.go
  internal/queue.go
  internal/serialization/data.go
  internal/serialization/serialization.go
  internal/set.go
  internal/topic.go
  samples/map/entry_processor/map_entryprocessor_example.go
  samples/map/listener/map_listener_example.go
  samples/map_soak.go
  samples/org_website_samples/entry_processor_sample.go
  samples/org_website_samples/portable_serializable_sample.go
  samples/org_website_samples/query_sample.go
  samples/org_website_samples/topic_sample.go
  samples/topic/topic_example.go
  tests/cluster_test.go
  tests/heartbeat_test.go
  tests/lifecycle_test.go
  tests/proxy/list/list_test.go
  tests/proxy/map/map_test.go
  tests/proxy/multi_map/multi_map_test.go
  tests/proxy/queue/queue_test.go
  tests/proxy/replicated_map/replicated_map_test.go
  tests/proxy/set/set_test.go
  tests/proxy/topic/topic_test.go
Labels: Type: Cleanup

#235 Time related API's converted to use time.* types.
  config/config.go
  core/api.go
  core/map.go
  core/multi_map.go
  core/queue.go
  core/replicated_map.go
  internal/cluster.go
  internal/common/util.go
  internal/common/util_test.go
  internal/heartbeat.go
  internal/map.go
  internal/multi_map.go
  internal/partition.go
  internal/protocol/core.go
  internal/protocol/custom_codec.go
  internal/queue.go
  internal/replicated_map.go
  samples/org_website_samples/queue_sample.go
  samples/topic/topic_example.go
  tests/heartbeat_test.go
  tests/invocation_test.go
  tests/lifecycle_test.go
  tests/proxy/map/map_member_down/map_member_down_test.go
  tests/proxy/map/map_test.go
  tests/proxy/multi_map/multi_map_test.go
  tests/proxy/queue/queue_test.go
  tests/proxy/replicated_map/replicated_map_test.go
  tests/proxy/topic/topic_test.go
Labels: Type: Enhancement

#238 Skip line after func
  internal/client.go
  internal/cluster.go
  internal/cluster_test.go
  internal/common/murmur.go
  internal/common/util.go
  internal/common/util_test.go
  internal/connection.go
  internal/connection_manager.go
  internal/heartbeat.go
  internal/invocation.go
  internal/lifecycle.go
  internal/listener.go
  internal/map.go
  internal/partition.go
  internal/predicates/predicates_impl.go
  internal/protocol/client_addmembershiplistener.go
  internal/protocol/core.go
  internal/protocol/custom_codec.go
  internal/protocol/custom_codec_test.go
  internal/protocol/message.go
  internal/protocol/message_test.go
  internal/proxy.go
  internal/replicated_map.go
  internal/ringbuffer.go
  rc/rc.go
  samples/map/listener/map_listener_example.go
  samples/map_soak.go
  samples/org_website_samples/identified_data_serializable_sample.go
  samples/serialization/identified/identified_data_serializable_example.go
  samples/serialization/portable/portable_example.go
  tests/cluster_test.go
  tests/invocation_test.go
  tests/lifecycle_test.go
  tests/listener_test.go
  tests/proxy/list/list_test.go
  tests/proxy/ringbuffer/ringbuffer_test.go
Labels: Type: Cleanup

#227 fix log and error messages
  internal/cluster.go
  internal/heartbeat.go
  internal/invocation.go
  internal/listener.go
  internal/partition.go
  samples/map_soak.go
Labels: Type: Cleanup

#228 fix some warnings from vet
  internal/common/buffer_util_test.go
  internal/invocation.go
  internal/protocol/custom_codec_test.go
  internal/protocol/message.go
  internal/ringbuffer.go
  internal/serialization/default_serializer_test.go
  internal/serialization/morphing_portable_reader_test.go
  internal/serialization/object_data_test.go
  internal/serialization/portable_serializer_test.go
  internal/serialization/serialization_test.go
  tests/compatibility/binary_compatibility_test.go
  tests/proxy/map/map_test.go
  tests/proxy/map/predicates_test.go
  tests/proxy/map/proxy_test.go
  tests/proxy/pn_counter/pn_counter_test.go
  tests/proxy/ringbuffer/ringbuffer_test.go
Labels: Type: Cleanup, Type: Defect

#226 change comments according to go conventions
  config/config.go
  config/flake_id_generator_config.go
  core/api.go
  core/errors.go
  core/list.go
  core/map.go
  core/member_selector.go
  core/multi_map.go
  core/pn_counter.go
  core/predicates/predicates.go
  core/queue.go
  core/replicated_map.go
  core/ringbuffer.go
  core/set.go
  core/topic.go
  hazelcast.go
  serialization/api.go
Labels: Type: Documentation

#249 remove server version when creating a cluster from rc
  tests/client_test.go
  tests/cluster_test.go
  tests/heartbeat_test.go
  tests/invocation_test.go
  tests/lifecycle_test.go
  tests/listener_test.go
  tests/proxy/list/list_test.go
  tests/proxy/map/map_member_down/map_member_down_test.go
  tests/proxy/map/map_test.go
  tests/proxy/multi_map/multi_map_test.go
  tests/proxy/queue/queue_test.go
  tests/proxy/replicated_map/replicated_map_test.go
  tests/proxy/ringbuffer/ringbuffer_test.go
  tests/proxy/set/set_test.go
  tests/proxy/topic/topic_test.go
Labels: Type: Enhancement

#206 add aggregate and project apis to map
  core/map.go
  internal/map.go
Labels: Type: Documentation, Type: Enhancement

#234 remove I prefix from interface names
  core/api.go
  core/cluster.go
  core/distributed_object.go
  core/flake_id_generator.go
  core/lifecycle.go
  core/list.go
  core/map.go
  core/member_selector.go
  core/multi_map.go
  core/pn_counter.go
  core/queue.go
  core/replicated_map.go
  core/ringbuffer.go
  core/set.go
  core/topic.go
  hazelcast.go
  internal/client.go
  internal/cluster.go
  internal/common/collection/util.go
  internal/connection.go
  internal/connection_manager.go
  internal/lifecycle.go
  internal/map.go
  internal/multi_map.go
  internal/pn_counter.go
  internal/protocol/core.go
  internal/proxy.go
  internal/proxy_manager.go
  internal/replicated_map.go
  samples/map/listener/map_listener_example.go
  samples/map_soak.go
  samples/org_website_samples/query_sample.go
  samples/org_website_samples/topic_sample.go
  samples/topic/topic_example.go
  tests/assert/assertions.go
  tests/cluster_test.go
  tests/proxy/flake_id_generator/flake_id_generator_test.go
  tests/proxy/list/list_test.go
  tests/proxy/map/map_member_down/map_member_down_test.go
  tests/proxy/map/map_test.go
  tests/proxy/multi_map/multi_map_test.go
  tests/proxy/pn_counter/pn_counter_test.go
  tests/proxy/queue/queue_test.go
  tests/proxy/replicated_map/replicated_map_test.go
  tests/proxy/ringbuffer/ringbuffer_test.go
  tests/proxy/set/set_test.go
  tests/proxy/topic/topic_test.go
Labels: Type: Cleanup

#231 add contributing and issue template
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
Labels: Type: Documentation

#244 close channels after a shutdown
  internal/client.go
  internal/cluster.go
  internal/connection.go
  internal/connection_manager.go
  internal/invocation.go
  internal/listener.go
  tests/client_test.go
Labels: Type: Defect, Type: Enhancement
