Repository hazelcast/hazelcast-go-client, pull requests merged in 2018-06, with the labels that each got.

#272 fix formatting and imports in codecs
  internal/proto/client_createproxy.go
  internal/proto/client_destroyproxy.go
  internal/proto/client_ping.go
  internal/proto/list_clear.go
  internal/proto/list_isempty.go
  internal/proto/list_removelistener.go
  internal/proto/list_size.go
  internal/proto/map_clear.go
  internal/proto/map_entryset.go
  internal/proto/map_evictall.go
  internal/proto/map_flush.go
  internal/proto/map_isempty.go
  internal/proto/map_removeentrylistener.go
  internal/proto/map_size.go
  internal/proto/multimap_clear.go
  internal/proto/multimap_entryset.go
  internal/proto/multimap_removeentrylistener.go
  internal/proto/multimap_size.go
  internal/proto/pncounter_getconfiguredreplicacount.go
  internal/proto/queue_clear.go
  internal/proto/queue_isempty.go
  internal/proto/queue_remainingcapacity.go
  internal/proto/queue_removelistener.go
  internal/proto/queue_size.go
  internal/proto/replicatedmap_clear.go
  internal/proto/replicatedmap_entryset.go
  internal/proto/replicatedmap_isempty.go
  internal/proto/replicatedmap_removeentrylistener.go
  internal/proto/replicatedmap_size.go
  internal/proto/ringbuffer_capacity.go
  internal/proto/ringbuffer_headsequence.go
  internal/proto/ringbuffer_remainingcapacity.go
  internal/proto/ringbuffer_size.go
  internal/proto/ringbuffer_tailsequence.go
  internal/proto/set_clear.go
  internal/proto/set_isempty.go
  internal/proto/set_removelistener.go
  internal/proto/set_size.go
  internal/proto/topic_removemessagelistener.go
Labels: Type: Cleanup

#275 return proper error when data type is unknown
  internal/serialization/serialization.go
  internal/serialization/serialization_test.go
Labels: Type: Defect

#281 add hazelcast property
  config/config.go
  config/property/client_properties.go
  config/property/hazelcast_properties.go
  config/property/hazelcast_properties_test.go
  config/property/hazelcast_property.go
  internal/client.go
  internal/heartbeat.go
  internal/invocation.go
  internal/listener.go
  test/heartbeat_test.go
  test/invocation_test.go
Labels: Type: Documentation, Type: Enhancement

#282 add go report to README
  README.md
Labels: Type: Documentation

#283 remove confusing error message from sendToAddress
  internal/invocation.go
Labels: Type: Cleanup
