Repository hazelcast/hazelcast-go-client, pull requests merged in 2018-02, with the labels that each got.

#155 change go client to hazelcast go client in readme
  samples/hello-world/README.md
Labels: Type: Enhancement

#163 fix readme, the link of license is broken
  README.md
Labels: Type: Documentation

#156 add List interface with Godocs
  core/IList.go
Labels: Type: Documentation, Type: Enhancement

#168 add Topic interface with GoDocs
  core/ITopic.go
  core/api.go
Labels: Type: Enhancement

#159 add ReplicatedMap interface with GoDocs
  core/replicated_map.go
Labels: Type: Documentation, Type: Enhancement

#160 add Set interface with Godocs
  core/ISet.go
Labels: Type: Documentation, Type: Enhancement

#165 add MultiMap interface with GoDocs
  core/multi_map.go
Labels: Type: Documentation, Type: Enhancement

#172 prevent serialization of data type
  internal/serialization/serialization.go
  internal/serialization/serialization_test.go
Labels: Type: Defect

#173 add PartitionSpecificProxy
  internal/list.go
  internal/map.go
  internal/partition.go
  internal/proxy.go
  internal/proxy_manager.go
Labels: Type: Enhancement
