Repository hazelcast/hazelcast-go-client, pull requests merged in 2018-03, with the labels that each got.

#176 add validateAndSerialize methods to simplify proxies
  core/IMap.go
  core/errors.go
  internal/common/consts.go
  internal/map.go
  internal/proxy.go
Labels: Type: Cleanup

#162 add Queue interface with Godocs
  core/IQueue.go
Labels: Type: Documentation, Type: Enhancement

#174 implement IList
  core/ICluster.go
  core/IList.go
  core/api.go
  core/errors.go
  hazelcast.go
  internal/client.go
  internal/cluster.go
  internal/common/collection/util.go
  internal/common/consts.go
  internal/list.go
  internal/map.go
  internal/protocol/core.go
  internal/protocol/list_iterator.go
  internal/protocol/list_listiterator.go
  internal/proxy.go
  tests/proxy/list/list_test.go
  tests/proxy/map/map_member_down/map_member_down_test.go
  tests/proxy/map/map_test.go
  tests/proxy/map/predicates_test.go
  tests/proxy/map/proxy_test.go
  tests/util.go
Labels: Type: Enhancement

#178 implement ISet with tests
  core/ISet.go
  hazelcast.go
  internal/client.go
  internal/list.go
  internal/proxy.go
  internal/proxy_manager.go
  internal/set.go
  tests/proxy/set/set_test.go
Labels: Type: Enhancement

#170 add Ringbuffer interface with GoDocs
  core/ringbuffer.go
Labels: Type: Documentation, Type: Enhancement

#179 implement ITopic with tests
  core/api.go
  hazelcast.go
  internal/client.go
  internal/protocol/core.go
  internal/protocol/topic_addmessagelistener.go
  internal/protocol/topic_messagetype.go
  internal/protocol/topic_publish.go
  internal/protocol/topic_removemessagelistener.go
  internal/proxy_manager.go
  internal/topic.go
  tests/proxy/topic/topic_test.go
Labels: Type: Enhancement

#184 Queue implementation and unit tests
  core/IQueue.go
  hazelcast.go
  internal/client.go
  internal/cluster.go
  internal/protocol/core.go
  internal/protocol/core_test.go
  internal/protocol/queue_addall.go
  internal/protocol/queue_addlistener.go
  internal/protocol/queue_clear.go
  internal/protocol/queue_compareandremoveall.go
  internal/protocol/queue_compareandretainall.go
  internal/protocol/queue_contains.go
  internal/protocol/queue_containsall.go
  internal/protocol/queue_drainto.go
  internal/protocol/queue_draintomaxsize.go
  internal/protocol/queue_isempty.go
  internal/protocol/queue_iterator.go
  internal/protocol/queue_messagetype.go
  internal/protocol/queue_offer.go
  internal/protocol/queue_peek.go
  internal/protocol/queue_poll.go
  internal/protocol/queue_put.go
  internal/protocol/queue_remainingcapacity.go
  internal/protocol/queue_remove.go
  internal/protocol/queue_removelistener.go
  internal/protocol/queue_size.go
  internal/protocol/queue_take.go
  internal/proxy_manager.go
  internal/queue.go
  rc/rc_test.go
  start-rc.sh
  tests/client_test.go
  tests/cluster_test.go
  tests/heartbeat_test.go
  tests/invocation_test.go
  tests/lifecycle_test.go
  tests/listener_test.go
  tests/proxy/list/list_test.go
  tests/proxy/map/map_member_down/map_member_down_test.go
  tests/proxy/map/map_test.go
  tests/proxy/queue/queue_test.go
  tests/proxy/set/set_test.go
  tests/proxy/topic/topic_test.go
  tests/util.go
Labels: Type: Enhancement

#186 log member list after a change in the list
  internal/cluster.go
  internal/protocol/core.go
Labels: Type: Enhancement

#185 implement Replicated Map with tests
  core/replicated_map.go
  hazelcast.go
  internal/client.go
  internal/common/util.go
  internal/map.go
  internal/protocol/replicatedmap_addentrylistener.go
  internal/protocol/replicatedmap_addentrylistenertokey.go
  internal/protocol/replicatedmap_addentrylistenertokeywithpredicate.go
  internal/protocol/replicatedmap_addentrylistenerwithpredicate.go
  internal/protocol/replicatedmap_addnearcacheentrylistener.go
  internal/protocol/replicatedmap_clear.go
  internal/protocol/replicatedmap_containskey.go
  internal/protocol/replicatedmap_containsvalue.go
  internal/protocol/replicatedmap_entryset.go
  internal/protocol/replicatedmap_get.go
  internal/protocol/replicatedmap_isempty.go
  internal/protocol/replicatedmap_keyset.go
  internal/protocol/replicatedmap_messagetype.go
  internal/protocol/replicatedmap_put.go
  internal/protocol/replicatedmap_putall.go
  internal/protocol/replicatedmap_remove.go
  internal/protocol/replicatedmap_removeentrylistener.go
  internal/protocol/replicatedmap_size.go
  internal/protocol/replicatedmap_values.go
  internal/proxy.go
  internal/proxy_manager.go
  internal/replicated_map.go
  tests/proxy/map/map_test.go
  tests/proxy/replicated_map/replicated_map_test.go
  tests/util.go
Labels: Type: Enhancement

#187 Ringbuffer codecs, implementation and test
  core/ringbuffer.go
  hazelcast.go
  internal/client.go
  internal/common/consts.go
  internal/protocol/ringbuffer_add.go
  internal/protocol/ringbuffer_addall.go
  internal/protocol/ringbuffer_capacity.go
  internal/protocol/ringbuffer_headsequence.go
  internal/protocol/ringbuffer_messagetype.go
  internal/protocol/ringbuffer_readmany.go
  internal/protocol/ringbuffer_readone.go
  internal/protocol/ringbuffer_remainingcapacity.go
  internal/protocol/ringbuffer_size.go
  internal/protocol/ringbuffer_tailsequence.go
  internal/proxy.go
  internal/proxy_manager.go
  internal/ringbuffer.go
  tests/proxy/ringbuffer/ringbuffer_test.go
Labels: Type: Enhancement

#182 implement Multimap
  core/multi_map.go
  hazelcast.go
  internal/client.go
  internal/map.go
  internal/multi_map.go
  internal/protocol/multimap_addentrylistener.go
  internal/protocol/multimap_addentrylistenertokey.go
  internal/protocol/multimap_clear.go
  internal/protocol/multimap_containsentry.go
  internal/protocol/multimap_containskey.go
  internal/protocol/multimap_containsvalue.go
  internal/protocol/multimap_delete.go
  internal/protocol/multimap_entryset.go
  internal/protocol/multimap_forceunlock.go
  internal/protocol/multimap_get.go
  internal/protocol/multimap_islocked.go
  internal/protocol/multimap_keyset.go
  internal/protocol/multimap_lock.go
  internal/protocol/multimap_messagetype.go
  internal/protocol/multimap_put.go
  internal/protocol/multimap_remove.go
  internal/protocol/multimap_removeentry.go
  internal/protocol/multimap_removeentrylistener.go
  internal/protocol/multimap_size.go
  internal/protocol/multimap_trylock.go
  internal/protocol/multimap_unlock.go
  internal/protocol/multimap_valuecount.go
  internal/protocol/multimap_values.go
  internal/proxy_manager.go
  tests/proxy/multi_map/multi_map_test.go
  tests/util.go
Labels: Type: Enhancement

#188 Code Samples for IList, ISet, IQueue, ReplicatedMap, MultiMap, Ringbuffer, ITopic
  core/ITopic.go
  samples/list/list_example.go
  samples/map/predicate/predicate_example.go
  samples/multi_map/multi_map_example.go
  samples/queue/queue_example.go
  samples/replicated_map/replicated_map_example.go
  samples/ringbuffer/ringbuffer_example.go
  samples/serialization/custom/custom_serializable_example.go
  samples/serialization/global/global_serializable_example.go
  samples/serialization/identified/identified_data_serializable_example.go
  samples/serialization/portable/portable_example.go
  samples/set/set_example.go
  samples/topic/topic_example.go
Labels: Type: Enhancement

#189 fix Ringbuffer readMany to make it more backward compatible API
  core/ringbuffer.go
  internal/ringbuffer.go
  tests/proxy/ringbuffer/ringbuffer_test.go
Labels: Type: Enhancement

#190 refactor file names in core
  core/cluster.go
  core/distributed_object.go
  core/lifecycle.go
  core/list.go
  core/map.go
  core/queue.go
  core/set.go
  core/topic.go
Labels: Type: Cleanup

#191 make internal methods private
  internal/client.go
  internal/cluster.go
  internal/connection.go
  internal/connection_manager.go
  internal/heartbeat.go
  internal/invocation.go
  internal/lifecycle.go
  internal/list.go
  internal/listener.go
  internal/loadbalancer.go
  internal/map.go
  internal/message_builder.go
  internal/message_builder_test.go
  internal/multi_map.go
  internal/partition.go
  internal/proxy.go
  internal/proxy_manager.go
  internal/queue.go
  internal/replicated_map.go
  internal/ringbuffer.go
  internal/set.go
  internal/topic.go
Labels: Type: Cleanup

#196 add flake id generator codecs
  internal/protocol/flakeidgenerator_messagetype.go
  internal/protocol/flakeidgenerator_newidbatch.go
Labels: Type: Enhancement

#199 check whether factory is able to create instance
  internal/serialization/default_serializer.go
  internal/serialization/default_serializer_test.go
Labels: Type: Defect

#195 add id generator interface
  core/flake_id_generator.go
Labels: Backport, Type: Documentation

#198 add PNCounter codecs
  internal/protocol/consts.go
  internal/protocol/pncounter_add.go
  internal/protocol/pncounter_get.go
  internal/protocol/pncounter_getconfiguredreplicacount.go
  internal/protocol/pncounter_messagetype.go
Labels: Type: Enhancement

#197 PNCounter interface with GoDocs
  core/errors.go
  core/pn_counter.go
Labels: Type: Documentation, Type: Enhancement

#201 implement flakeIdGenerator with tests
  config/config.go
  config/flake_id_generator_config.go
  hazelcast.go
  internal/client.go
  internal/error.go
  internal/flake_id/auto_batcher.go
  internal/flake_id/auto_batcher_test.go
  internal/flake_id_generator.go
  internal/proxy_manager.go
  start-rc.sh
  tests/proxy/flake_id_generator/flake_id_generator_test.go
  tests/util.go
Labels: Type: Enhancement

#203 add flake id generator sample
  samples/flake_id_generator/flake_id_generator_sample.go
Labels: Type: Enhancement
