Repository hazelcast/hazelcast-go-client, pull requests merged in 2018-07, with the labels that each got.

#289 remove duplicate vet from build.sh
  build.sh
Labels: Type: Cleanup

#279 implement cloud discovery
  .gometalinter.json
  config/client_cloud.go
  config/config.go
  config/property/client_properties.go
  config/property/hazelcast_property.go
  core/errors.go
  internal/address_provider.go
  internal/address_translator.go
  internal/client.go
  internal/cluster.go
  internal/cluster_test.go
  internal/connection_manager.go
  internal/discovery/hazelcast_cloud_discovery.go
  internal/discovery/hz_cloud_addr_provider.go
  internal/discovery/hz_cloud_addr_provider_test.go
  internal/discovery/hz_cloud_addr_translator.go
  internal/discovery/hz_cloud_addr_translator_test.go
  test/discovery/cloud_config_test.go
Labels: Type: Enhancement

#293 add missing alive check to connection manager
  internal/connection_manager.go
  internal/invocation.go
  test/invocation_test.go
Labels: Type: Test-Failure

#291 simplify and fix regex in metalinter
  .gometalinter.json
Labels: Type: Cleanup

#299 return error in getDistributedObject when no service found
  core/errors.go
  internal/client.go
  internal/proxy_manager.go
  test/client_test.go
Labels: Type: Defect

#296 add custom credentials and credentials struct
  config/client_cloud_config.go
  config/client_security_config.go
  config/config.go
  internal/client.go
  internal/connection_manager.go
  internal/proto/client_authenticationcustom.go
  security/base_credentials.go
  security/credentials.go
  security/username_passw_creds.go
  start-rc.sh
  test/client_authentication_test.go
  test/client_test.go
Labels: Type: Enhancement

#292 add hazelcast cloud discovery example
  sample/hzclouddiscovery/cloud_discovery_example.go
Labels: Type: Enhancement

#303 add custom cloud url option for internal testing
  internal/client.go
  internal/discovery/hazelcast_cloud_discovery.go
  internal/discovery/hz_cloud_addr_provider.go
  internal/discovery/hz_cloud_addr_translator.go
  sample/hzclouddiscovery/cloud_discovery_example.go
  test/discovery/cloud_config_test.go
Labels: Type: Enhancement

#271 update scripts
  README.md
  local-test.sh
  start-rc.sh
Labels: Type: Enhancement

#305 increase coverage and reduce test time
  config/flake_id_generator_config.go
  config/property/hazelcast_properties_test.go
  internal/vector_clock.go
  test/client_test.go
  test/cluster_test.go
  test/config_test.go
  test/proxy/flakeidgen/flake_id_generator_test.go
  test/proxy/pncounter/pn_counter_test.go
Labels: Type: Enhancement

#307 enhance tests
  internal/invocation.go
  internal/invocation_test.go
  internal/loadbalancer_test.go
  test/discovery/cloud_discovery_test.go
  test/proxy/set/set_test.go
  test/proxy/topic/topic_test.go
Labels: Type: Enhancement

#308 add more custom credentials tests
  security/username_passw_creds.go
  test/client_authentication_test.go
Labels: Type: Enhancement

#304 remove unused isNoOtherProvider variable
  internal/address_provider.go
  internal/client.go
  test/cluster_test.go
Labels: Type: Cleanup
