Repository hazelcast/hazelcast-go-client, pull requests merged in 2018-11, with the labels that each got.

#374 add some data structure docs to README
  README.md
Labels: Type: Documentation

#376 decrease statistics period time in test
  test/statistics/client_statistics_test.go
Labels: Type: Defect

#375 Enhance readme
  README.md
Labels: Type: Documentation

#378 "For more details" in Section 1.3 should be enhanced.
  README.md
Labels: Type: Documentation

#381 add statistics example
  sample/statistics/statistics_example.go
Labels: Type: Documentation

#380 add client statistics part in README
  README.md
Labels: Type: Documentation

#382 try to connect cluster even if the error is authentication error
  internal/cluster.go
  test/cluster_test.go
  test/config_test.go
Labels: Type: Defect

#384 Fix broken TLS/SSL link in README
  README.md
Labels: Type: Documentation

#385 Add missing data structure links in table of contents
  README.md
Labels: Type: Documentation

#377 change samples in README to be consistent with other clients
  README.md
  sample/orgwebsite/identified_data_serializable_sample.go
  sample/orgwebsite/portable_serializable_sample.go
Labels: Type: Documentation

#386 enhance README
  README.md
Labels: Type: Documentation

#387 enhance membertool in README
  README.md
Labels: Type: Documentation

#388 Final retouches for the current content.
  README.md
Labels: Type: Documentation

#379 add default certificates trust tests
  start-rc.sh
  test/ssl/client_ssl_authentication_test.go
  test/ssl/letsencrypt.jks
Labels: Type: Enhancement

#383 add assert eventually and remove sleeps
  test/client_test.go
  test/cluster_test.go
  test/invocation_test.go
  test/listener_test.go
  test/proxy/map/map_test.go
  test/proxy/multimap/multi_map_test.go
  test/proxy/reliabletopic/clusterrestart/cluster_restart_test.go
  test/proxy/reliabletopic/reliable_topic_test.go
  test/proxy/replicatedmap/replicated_map_test.go
  test/util.go
Labels: Type: Cleanup

#389 add client properties to README
  README.md
Labels: Type: Documentation

#390 Refactor 1.2.1 in README
  README.md
Labels: Type: Documentation

#395 Clarify statistics part in README
  README.md
Labels: Type: Documentation

#399 Update client version as 0.5
  internal/connection_manager.go
Labels: Type: Enhancement
