Repository hazelcast/hazelcast-go-client, pull requests merged in 2019-03, with the labels that each got.

#455 Add JSON part to README
  README.md
Labels: Type: Documentation

#456 Clarify usage of log levels
  README.md
  config/logger_config.go
  core/logger/default_logger.go
  internal/client.go
  test/logger/logger_test.go
  test/logger/no_logger_test.go
Labels: Type: Documentation

#460 Json API update
  README.md
  core/api.go
  internal/listener.go
  internal/proxy.go
  internal/util/nilutil/nil_test.go
  internal/util/nilutil/util.go
  sample/hazelcastJSON/hazelcastJSON.go
  serialization/internal/default_serializer.go
  serialization/internal/serialization.go
  test/client/json_test.go
  test/proxy/map/map_test.go
  test/proxy/map/predicates_test.go
Labels: Type: Defect

#461 update year in new added json related files
  internal/util/nilutil/nil_test.go
  internal/util/nilutil/util.go
  test/client/json_test.go
Labels: Type: Cleanup
