Repository hazelcast/hazelcast-go-client, pull requests merged in 2019-02, with the labels that each got.

#433 add positional output tests
  serialization/internal/object_data_test.go
Labels: Type: Enhancement

#435 Remove membertool section from README
  README.md
Labels: Type: Documentation

#441 Fix data race in invocation not sent test
  test/invocation_test.go
Labels: Type: Defect

#436 Remove unnecessary vendor folder check
  build.sh
Labels: Type: Enhancement

#442 Remove extra line in logs
  core/logger/default_logger.go
Labels: Type: Defect

#448 Collect RLimit for only linux and darwin
  internal/statistics.go
  internal/statistics_osmetric.go
  internal/statistics_other.go
Labels: Type: Defect

#447 Change port type from int32 to int
  internal/discovery/hazelcast_cloud_discovery.go
  internal/proto/core.go
  internal/proto/custom_codec.go
  internal/proto/custom_codec_test.go
  internal/util/iputil/util.go
  internal/util/iputil/util_test.go
  test/client/cluster_test.go
Labels: Type: Defect

#445 Remove isValidIP check to allow hostnames in addresses
  internal/cluster.go
  internal/ringbuffer_test.go
  internal/util/colutil/util_test.go
  internal/util/iputil/util.go
  internal/util/iputil/util_test.go
  test/client/client_test.go
  test/client/cluster_test.go
Labels: Type: Enhancement

#452 Remove missing linters from gometalinter
  .gometalinter.json
  test/testutil/util.go
Labels: Type: Defect

#453 Remove register in reliable topic test
  test/proxy/reliabletopic/leakage/leakage_test.go
  test/proxy/reliabletopic/reliable_topic_test.go
Labels: Type: Defect
