Repository hazelcast/hazelcast-go-client, pull requests merged in 2021-08, with the labels that each got.

#612 Return same proxy struct instance from Get calls
  .github/workflows/test-all.yaml
  client_it_test.go
  proxy_manager.go
Labels: Type: Defect, Priority: High, Source: Internal

#608 Add failover config support
  client.go
  client_it_test.go
  cluster/failover_config.go
  cluster/failover_config_test.go
  config.go
  config_test.go
  events.go
  internal/cloud/address_provider.go
  internal/cloud/address_translator.go
  internal/cluster/address_provider.go
  internal/cluster/address_translator.go
  internal/cluster/cluster_service.go
  internal/cluster/connection_manager.go
  internal/cluster/events.go
  internal/cluster/failover_service.go
  internal/cluster/partition_service.go
  internal/it/util.go
Labels: Type: Enhancement

#611 Add FlakeIDGenerator [API-482]
  client.go
  config.go
  config_test.go
  export_test.go
  flake_id_generator.go
  flake_id_generator_it_test.go
  flake_id_generator_test.go
  internal/proto/codec/flake_id_generator_new_id_batch_codec.go
  internal/util/validationutil/util.go
  internal/util/validationutil/util_test.go
  proxy.go
  proxy_manager.go
Labels: Type: Enhancement, Source: Internal
