Repository hazelcast/hazelcast-go-client, pull requests merged in 2021-12, with the labels that each got.

#699 [1.2.0] Implement ExecuteOnKey map method [API-1032]
  examples/map/execute_on_key/entry_processor.go
  examples/map/execute_on_key/main.go
  map_it_test.go
  proxy_map.go
Labels: to-jira

#704 [1.2.0] [EASY] Updated logger documentation
  examples/logger/custom_logger/main.go
  internal/logger/default_logger.go
  internal/logger/default_logger_test.go
  logger/doc.go
  logger/logger.go
  logger/logger_config.go
  logger/logger_test.go
Labels: Type: Documentation, to-jira

#702 [1.2.0] [EASY] Set TTL return [API-1081]
  map_it_test.go
  proxy_map.go
Labels: to-jira

#696 [1.2.0] Event ordering
  client_it_test.go
  internal/invocation/invocation_service.go
  internal/invocation/stripe_executor.go
  internal/invocation/stripe_executor_test.go
  internal/stats/stats_service_test.go
Labels: Type: Defect, to-jira
