Repository hazelcast/hazelcast-go-client, pull requests merged in 2023-03, with the labels that each got.

#920 Add TLS/SSL code samples and documentation. [API-1837]
  doc.go
  examples/ssl/mutual_authentication/main.go
  examples/ssl/simple/main.go
Labels: Type: Enhancement, Type: Documentation

#901 Add CP Subsystem AtomicLong support [API-1633] [API-1631]
  atomic_long_it_test.go
  client.go
  examples/cp/atomic_long.go
  internal/cp/proxy.go
  internal/cp/proxy_atomic_long.go
  internal/cp/proxy_factory.go
  internal/cp/proxy_factory_test.go
  internal/cp/subsystem.go
  internal/cp/types/group_id.go
  internal/cp/types/raft_group_id.go
  internal/it/atomic_long.go
  internal/it/util.go
  internal/proto/codec/atomic_long_add_and_get_codec.go
  internal/proto/codec/atomic_long_alter_codec.go
  internal/proto/codec/atomic_long_apply_codec.go
  internal/proto/codec/atomic_long_compare_and_set_codec.go
  internal/proto/codec/atomic_long_get_and_add_codec.go
  internal/proto/codec/atomic_long_get_and_set_codec.go
  internal/proto/codec/atomic_long_get_codec.go
  internal/proto/codec/cp_group_create_cp_group_codec.go
  internal/proto/codec/cp_group_destroy_cp_object_codec.go
  internal/proto/codec/raft_group_id_codec.go
Labels: Type: Enhancement, Priority: Medium, Estimation: L, Source: Internal

#943 Set the ServerName automatically for Viridian [API-1946]
  README.md
  cluster/cluster_config.go
  cluster/network_config.go
  config_test.go
  examples/cloud/main.go
Labels: to-jira

#919 Add String() and Float64() methods for types.Decimal [API-1835]
  types/decimal.go
  types/decimal_test.go
Labels: Type: Enhancement
